# Generated by Django 5.0.2 on 2024-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capstone", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
