# Generated by Django 5.0.2 on 2024-02-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capstone", "0003_career_delete_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name="follower",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="user",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Follower",
        ),
    ]
