# Generated by Django 5.0.2 on 2024-02-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capstone", "0004_referral_remove_follower_follower_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Career",
            new_name="Timeline",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
