# Generated by Django 5.0.2 on 2024-02-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capstone", "0006_referral_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="subject",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="referral",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
