# Generated by Django 5.0.2 on 2024-02-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capstone", "0008_alter_referral_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="referral",
            old_name="author",
            new_name="name",
        ),
    ]
