# Generated by Django 5.0.2 on 2024-02-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capstone", "0009_rename_author_referral_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
